output "cluster_endpoint" {
  description = "Endpoint for EKS control plane"
  value = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane"
  value = module.eks.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module"
  value = module.eks.kubeconfig
}

output "region" {
  description = "AWS region"
  value = var.aws_region
}

# Deployment 등은 kubectl 로 하는것이 좋을것같다
# 참고자료 https://www.youtube.com/watch?v=Qy2A_yJH5-o
# grab our EKS config
# aws eks update-kubeconfig --name getting-started-eks --region ap-northeast-2